/**
 * Cross-platform compatibility test for UnifiedId (TypeScript vs C#).
 * All expected values were generated by the C# implementation.
 *
 * Run: npx tsx test/UnifiedId.test.ts
 *   or: npx ts-node test/UnifiedId.test.ts
 */

import { UnifiedId } from "../src/Unified/UnifiedId";

let passed = 0;
let failed = 0;

function assertEqual(label: string, actual: string | bigint | number | null, expected: string | bigint | number | null) {
  const a = String(actual);
  const e = String(expected);
  if (a === e) {
    passed++;
  } else {
    failed++;
    console.error(`  FAIL: ${label}\n    expected: ${e}\n    actual:   ${a}`);
  }
}

function section(name: string) {
  console.log(`\n=== ${name} ===`);
}

// ─── Constructor Tests ───────────────────────────────────────────────

section("Constructor Tests");

assertEqual("ulong(0) toString", new UnifiedId(0n).toString(), "0000000000000");
assertEqual("ulong(max) toString", new UnifiedId(0xFFFFFFFFFFFFFFFFn).toString(), "FVVVVVVVVVVVV");
assertEqual("ulong(max) toUInt64", new UnifiedId(0xFFFFFFFFFFFFFFFFn).toUInt64(), 18446744073709551615n);
assertEqual("ulong(max-1) toString", new UnifiedId(0xFFFFFFFFFFFFFFFFn - 1n).toString(), "FVVVVVVVVVVVU");
assertEqual("ulong(max-1) toUInt64", new UnifiedId(0xFFFFFFFFFFFFFFFFn - 1n).toUInt64(), 18446744073709551614n);
assertEqual("ulong(1) toString", new UnifiedId(1n).toString(), "0000000000001");
assertEqual("ulong(8) toString", new UnifiedId(8n).toString(), "0000000000008");
assertEqual("ulong(12345678901234) toString", new UnifiedId(12345678901234n).toString(), "0000B79PSSBVI");
assertEqual("ulong(12345678901234) toUInt64", new UnifiedId(12345678901234n).toUInt64(), 12345678901234n);

// From signed long (reinterpret bits)
// long.MinValue = -9223372036854775808 => unsigned = 9223372036854775808 = 0x8000000000000000
assertEqual("long(min) toString", new UnifiedId(BigInt.asUintN(64, -9223372036854775808n)).toString(), "8000000000000");
assertEqual("long(min) toInt64", new UnifiedId(BigInt.asUintN(64, -9223372036854775808n)).toInt64(), -9223372036854775808n);
// long(-1) => unsigned = 0xFFFFFFFFFFFFFFFF
assertEqual("long(-1) toString", new UnifiedId(BigInt.asUintN(64, -1n)).toString(), "FVVVVVVVVVVVV");
assertEqual("long(-1) toInt64", new UnifiedId(BigInt.asUintN(64, -1n)).toInt64(), -1n);

// ─── Parse Tests ────────────────────────────────────────────────────

section("Parse Tests");

const parseTests: [string, string, bigint, bigint][] = [
  ["FVVVVVVVVVVVU", "FVVVVVVVVVVVU", 18446744073709551614n, -2n],
  ["FVSRVVVVVVVVU", "FVSRVVVVVVVVU", 18443225636500668414n, -3518437208883202n],
  ["0000000000000", "0000000000000", 0n, 0n],
  ["8000000000000", "8000000000000", 9223372036854775808n, -9223372036854775808n],
  ["0000000000008", "0000000000008", 8n, 8n],
];

for (const [input, expStr, expUInt64, expInt64] of parseTests) {
  const id = UnifiedId.parse(input);
  assertEqual(`Parse(${input}) toString`, id.toString(), expStr);
  assertEqual(`Parse(${input}) toUInt64`, id.toUInt64(), expUInt64);
  assertEqual(`Parse(${input}) toInt64`, id.toInt64(), expInt64);
}

// Parse validation
section("Parse Validation");
assertEqual("Parse empty => empty", UnifiedId.parse("").toString(), "0000000000000");

let threw = false;
try { UnifiedId.parse("VVVVVVVVVVVVV"); } catch { threw = true; }
assertEqual("Parse(VVVVVVVVVVVVV) throws", threw, true);

threw = false;
try { UnifiedId.parse("FVVVVVVVVVVVUN"); } catch { threw = true; }
assertEqual("Parse(too long) throws", threw, true);

// C# uppercases input via ToUpperInvariant(), so lowercase is accepted
assertEqual("Parse(lowercase) accepts", UnifiedId.parse("FVVVVVVVVVVVu").toString(), "FVVVVVVVVVVVU");

threw = false;
try { UnifiedId.parse("FVVVVVVVVVVVW"); } catch { threw = true; }
assertEqual("Parse(invalid char W) throws", threw, true);

threw = false;
try { UnifiedId.parse("GVVVVVVVVVVVU"); } catch { threw = true; }
assertEqual("Parse(first char G) throws", threw, true);

threw = false;
try { UnifiedId.parse("WVVVVVVVVVVVU"); } catch { threw = true; }
assertEqual("Parse(first char W) throws", threw, true);

// ─── TryParse Tests ─────────────────────────────────────────────────

section("TryParse Tests");
assertEqual("TryParse valid", UnifiedId.tryParse("FVVVVVVVVVVVU")?.toString(), "FVVVVVVVVVVVU");
assertEqual("TryParse empty", UnifiedId.tryParse(""), null);
assertEqual("TryParse VVVVVVVVVVVVV", UnifiedId.tryParse("VVVVVVVVVVVVV"), null);
assertEqual("TryParse too long", UnifiedId.tryParse("FVVVVVVVVVVVUN"), null);
// C# uppercases input, so lowercase parses successfully
assertEqual("TryParse lowercase", UnifiedId.tryParse("FVVVVVVVVVVVu")?.toString(), "FVVVVVVVVVVVU");
assertEqual("TryParse invalid W", UnifiedId.tryParse("FVVVVVVVVVVVW"), null);
assertEqual("TryParse first G", UnifiedId.tryParse("GVVVVVVVVVVVU"), null);
assertEqual("TryParse first W", UnifiedId.tryParse("WVVVVVVVVVVVU"), null);

// ─── FromString (FNV hash) ──────────────────────────────────────────

section("FromString Tests");

const fromStringTests: [string, string, bigint][] = [
  ["UnifiedId", "12H6B89SSEV2O", 1244342883432496216n],
  ["hello", "A8C6O8Q0ALF8B", 11831194018420276491n],
  ["Hello World", "3QM6USSMKS317", 4420528118743043111n],
  ["test", "FJPN6TSCNOAP5", 18007334074686647077n],
  ["a", "AUOUS9I303R4C", 12638187200555641996n],
  ["abc", "EE7T2342K2LQB", 16654208175385433931n],
];

for (const [text, expStr, expUInt64] of fromStringTests) {
  const id = UnifiedId.fromString(text);
  assertEqual(`FromString("${text}") toString`, id.toString(), expStr);
  assertEqual(`FromString("${text}") toUInt64`, id.toUInt64(), expUInt64);
}

// ─── FromBytes ──────────────────────────────────────────────────────

section("FromBytes Tests");

const fromBytesTests: [number[], string, bigint][] = [
  [[10], "AUOU79I303I6T", 12638164110811449565n],
  [[0, 1, 2, 3], "48T9IFUCE0L0H", 4932904490461320209n],
  [[255], "AUP3I9I305QRE", 12638352127299873646n],
  [[1, 2, 3, 4, 5, 6, 7, 8], "7TD8GHCR8KU7D", 9130222009665091821n],
];

for (const [bytes, expStr, expUInt64] of fromBytesTests) {
  const id = UnifiedId.fromBytes(new Uint8Array(bytes));
  assertEqual(`FromBytes([${bytes}]) toString`, id.toString(), expStr);
  assertEqual(`FromBytes([${bytes}]) toUInt64`, id.toUInt64(), expUInt64);
}

// ─── FromUInt64 ─────────────────────────────────────────────────────

section("FromUInt64 Tests");

const fromUInt64Tests: [bigint, string, bigint][] = [
  [1n, "8JJ9H54EILRT4", 9929646806074584996n],
  [42n, "FUEMTDCROJMNF", 18391255480883862255n],
  [255n, "905LHIRHKJ8OQ", 10382681252565721882n],
  [65536n, "COCCJVST2GSSC", 14713704181997794188n],
  [18446744073709551615n, "8PT8QHFUA721T", 10157053723145373757n],
];

for (const [num, expStr, expUInt64] of fromUInt64Tests) {
  const id = UnifiedId.fromUInt64(num);
  assertEqual(`FromUInt64(${num}) toString`, id.toString(), expStr);
  assertEqual(`FromUInt64(${num}) toUInt64`, id.toUInt64(), expUInt64);
}

// ─── FromInt64 ──────────────────────────────────────────────────────

section("FromInt64 Tests");

const fromInt64Tests: [bigint, string, bigint][] = [
  [1n, "8JJ9H54EILRT4", 9929646806074584996n],
  [-1n, "8PT8QHFUA721T", 10157053723145373757n],
  [-9223372036854775808n, "AHHRO68K1IO25", 12161821475553763397n],
  [9223372036854775807n, "8PTCQHFUA8ODT", 10157194460633784765n],
  [42n, "FUEMTDCROJMNF", 18391255480883862255n],
];

for (const [num, expStr, expUInt64] of fromInt64Tests) {
  const id = UnifiedId.fromInt64(num);
  assertEqual(`FromInt64(${num}) toString`, id.toString(), expStr);
  assertEqual(`FromInt64(${num}) toUInt64`, id.toUInt64(), expUInt64);
}

// ─── FromGuid ───────────────────────────────────────────────────────

section("FromGuid Tests");

const fromGuidTests: [string, string, bigint][] = [
  ["550e8400-e29b-41d4-a716-446655440000", "9N4IQBCEEVBTG", 11210121769852579760n],
  ["12345678-1234-1234-1234-123456789abc", "9R77PGSNUOHI5", 11357226719341463109n],
  ["ffffffff-ffff-ffff-ffff-ffffffffffff", "DCO3L13QQ3Q2L", 15447475403222018133n],
  ["00000001-0000-0000-0000-000000000000", "3I8G9U56UKJ14", 4116863941369023524n],
];

for (const [guid, expStr, expUInt64] of fromGuidTests) {
  const id = UnifiedId.fromGuid(guid);
  assertEqual(`FromGuid(${guid}) toString`, id.toString(), expStr);
  assertEqual(`FromGuid(${guid}) toUInt64`, id.toUInt64(), expUInt64);
}

// ─── Partition Tests ────────────────────────────────────────────────

section("Partition Tests");

const pid = UnifiedId.parse("FVSRVVVVVVVVU");
assertEqual("PartitionKey(3)", pid.partitionKey(3), "FVS");
assertEqual("PartitionKey(4)", pid.partitionKey(4), "FVSR");
assertEqual("PartitionKey(1)", pid.partitionKey(1), "F");
assertEqual("PartitionNumber(32768)", pid.partitionNumber(32768n), 32761n);
assertEqual("PartitionNumber(100)", pid.partitionNumber(100n), 99n);
assertEqual("PartitionNumber(99)", pid.partitionNumber(99n), 98n);
assertEqual("PartitionNumber(3)", pid.partitionNumber(3n), 2n);
assertEqual("PartitionNumberAsString(9999)", pid.partitionNumberAsString(9999), "9997");
assertEqual("PartitionNumberAsString(100)", pid.partitionNumberAsString(100), "099");
assertEqual("PartitionNumberAsString(99)", pid.partitionNumberAsString(99), "98");
assertEqual("PartitionNumberAsString(3)", pid.partitionNumberAsString(3), "2");

// ─── Equality / Comparison Tests ────────────────────────────────────

section("Equality & Comparison Tests");

const eqId = UnifiedId.parse("FVVVVVVVVVVVV");
assertEqual("equals string", eqId.equals("FVVVVVVVVVVVV"), true);
assertEqual("equals bigint", eqId.equals(18446744073709551615n), true);
assertEqual("equals self", eqId.equals(eqId), true);
assertEqual("equals clone", eqId.equals(eqId.clone()), true);

const cmpA = new UnifiedId(1n);
const cmpB = new UnifiedId(2n);
assertEqual("compareTo less", cmpA.compareTo(cmpB), -1);
assertEqual("compareTo greater", cmpB.compareTo(cmpA), 1);
assertEqual("compareTo equal", cmpA.compareTo(new UnifiedId(1n)), 0);

// ─── NewId (non-deterministic, just check not empty) ────────────────

section("NewId Tests");

const newId = UnifiedId.newId();
assertEqual("newId not empty", newId.equals(UnifiedId.Empty), false);
assertEqual("newId length 13", newId.toString().length, 13);

const newId2 = UnifiedId.newId();
assertEqual("two newIds differ", newId.equals(newId2), false);

// ─── Roundtrip Tests ────────────────────────────────────────────────

section("Roundtrip Tests");

// Parse -> toString roundtrip
const rtHexes = ["FVVVVVVVVVVVU", "FVSRVVVVVVVVU", "0000000000000", "8000000000000", "0000000000008", "0000B79PSSBVI"];
for (const hex of rtHexes) {
  assertEqual(`Roundtrip ${hex}`, UnifiedId.parse(hex).toString(), hex);
}

// toJSON
const jsonId = UnifiedId.parse("FVVVVVVVVVVVU");
assertEqual("toJSON", jsonId.toJSON(), "FVVVVVVVVVVVU");
assertEqual("JSON.stringify", JSON.stringify({ id: jsonId }), '{"id":"FVVVVVVVVVVVU"}');

// ─── Summary ────────────────────────────────────────────────────────

console.log(`\n${"=".repeat(50)}`);
console.log(`Results: ${passed} passed, ${failed} failed, ${passed + failed} total`);
if (failed > 0) {
  console.log("SOME TESTS FAILED!");
  process.exit(1);
} else {
  console.log("ALL TESTS PASSED!");
}
